version: "3.7"

services:
  actions:
    build:
        context : .
    image: xtechsample/actions
    command: ["server","--port", ":3050", "--saddr","http://176.9.137.77:4000/", "--eaddr", "176.9.137.77:2379"] #,
    restart: always
    network_mode: host

  rtmp:
    image: gwuhaolin/livego
    command : "--config_file /etc/livego.yaml"
    volumes:
     - ./cfgs/rtmp/livego.yaml:/etc/livego.yaml
    network_mode: host